### ISSUE TITLE
Support for CronJobs

### ISSUE THREAD

**Issue by stuart-warren** [pusher/wave#27]
Add support for updating CronJobs as well as Deployments

**Comment by gargath** [comment]
Hello Stuart,

Thanks for raising this.
Could you elaborate a little bit on what your use case is?

For Deployments, Wave ensures that on configuration update, all running Pods are eventually restarted to pick up the new configuration.

For a CronJob, Pods are created when the timer triggers and then run to completion.
If configuration changes between two invocations, the next one will by default use the new values.

In what situation would you need Wave to interact with CronJobs and what would the desired behaviour be in that case?

**Comment by stuart-warren** [comment]
you make a good point! 🤦‍♂️
