### ISSUE TITLE
Example configuration doesn't work with kustomize

### ISSUE THREAD

**Issue by AssafKatz3** [pusher/wave#36]
Hi,
Running "kustomize build" on example configuration don't work since it uses "../rbac" and "../manager" while kustomize (2.0.1) assumes that it is under the folder which contains the kustomization.yaml, the error is:

> Error: rawResources failed to read Resources: Load from path ../manager/manager.yaml failed: security; file '../manager/manager.yaml' is not in or below '/home/wave-master/config/default'

I moved both folder under default and modify the path accordingly.
Thanks

**Comment by JoelSpeed** [comment]
I'm not a kustomize user personally. I wonder if updating our `kubebuilder` code generation would fix this 🤔 

@AssafKatz3 Could you maybe go into more detail about the changes you made? I'm not following
Perhaps a PR if you have the time?

**Comment by AssafKatz3** [comment]
The changes (with changes for #37) are [here](https://github.com/pusher/wave/files/2875395/config.zip)

**Comment by meganwalker-ibm** [comment]
I've just opened a PR for this in #39 to show what worked for me in fixing the error.
