### ISSUE TITLE
how to initialize deployments' annotation on the PodTemplate

### ISSUE THREAD

**Issue by gaorong** [pusher/wave#54]
this is an awesome project, I'll have a try in my cluster. but I also have a question about the mechanism of initializing the deployments' hash annotation. 

When a new deployment first comes, it will create some pod without the hash annotation.  then wave will take over this deployments' config management, and add a hash annotation in podtemplate. Does this mean a new-created deployment will always do a rolling update immediately after it creates.  

thanks

**Comment by JoelSpeed** [comment]
At present, the behaviour is as you describe, a newly created deployment immediately gets a rollout. That said, Wave should react quickly enough that none of the pods without hash actually get a chance to be started.

There is a potential fix for this if we were to create a mutating admission webhook which could update the hash on updates to deployments though this would also happen when wave sends an update so the logic would be doubled 😅

We haven't seen any issues with the existing behaviour in our clusters so far but do keep us updated if you see any issues

**Comment by gaorong** [comment]
thanks, got it.
